services:
  - type: web
    name: ats-resume-analyzer
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: gunicorn main:app
